### ISSUE TITLE
RGB logic is reversed on the Tilda

### ISSUE THREAD

**Issue by SupraJames** [Tingenek/EMFBadge#1]
Hey, found your blog and using it to help me create my own basic project on the Tilda.

Just a note to say the RGB test produces wrong colours. The fix is to invert the RGB values in setColor:

void setColor(int red, int green, int blue)
{
 analogWrite(LED1_RED, 255-red);
 analogWrite(LED1_GREEN, 255-green);
 analogWrite(LED1_BLUE, 255-blue); 
}

Cheers :)

**Comment by Tingenek** [comment]
Thanks. The badges were fun.
